version: '3.4'

services:
  notejamv3:
    image: notejamv3
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      
  nginx:
     build: ./nginx
     container_name: nginx
     restart: always
     ports:
       - "80:80"
   
    
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/