version: '3.4'

services:
  notejamv3:
    image: notejamv3
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./db/:/root/db/
    Ports:
      - 5000:5000

  nginx:
    image: nginx 
    build: 
      context:
      dockerfile: ./Nginx/Dockerfile
    ports:
      - "80:80"
   
